### ISSUE TITLE
Workflow to create a workflow

### ISSUE THREAD

**Issue by twocs** [warpdotdev/workflows#124]
### Is this a new workflow or an update?

New

### What is the name of the workflow?

warp > workflow

### What should the workflow do?

Initialise a new workflow. Basically you can pass in some flags and it will create a local yaml file. Possibly needed to support this is a warp settings file that sets the common details needed in the yaml template such as author. However, is this a new workflow or a CLI tool for warp, I don't even know? Copying a workflow template from the internet and saving it in ~/.warp/workflows, then editing it, does not seem like how workflows should work in 2022.

### What does it do (only if it's an update)?

If it's a CLI tool, I expect `warp workflow init --author "Tom Smith" --type "fish" --cmd "echo 'Hello Warp!"` that will initialise a workflow.  

At minimum I'd expect a workflow that will download a workflow template to `~/.warp` that I could then open in an editor.

**Comment by twocs** [comment]
Alternately, to create a workflow, when you browse workflows, "My Workflows" could have an "Add New Workflow" button.

<img width="714" alt="image" src="https://user-images.githubusercontent.com/72763/208015035-3d58d057-0d4e-4609-b2ac-ba1025737618.png">

Similarly there could be an option to open my existing workflow to edit it.

**Comment by alokedesai** [comment]
Hey @twocs, thanks for the feedback. I love this idea! We've been thinking about creating a `warp` CLI for a while to automate various actions in the app and I think this would be a great fit for it. I'm going to close this out since it's not related to the workflow definitions themselves, but feel free to create an issue in our main repo (warpdotdev/warp) for updates!
